### ISSUE TITLE
Examples won't build, template broken, poor quality

### ISSUE THREAD

**Issue by imanpeeman** [forcedotcom/SalesforceMobileSDK-Windows#189] opened 2016-02-03 17:51 UTC
The link to the visual studio template file is broken

**Comment by imanpeeman** [comment] 2016-02-03 19:38
[can't change previous post]
SDK doesn't support Universal Apps, connected services fails as well.

I'm off.

**Comment by kchitalia** [comment] 2016-02-04 19:11
@imanpeeman The latest SDK supports Universal Apps. You will need Windows 10 and Visual Studio 2015 to run the latest SDK. Are you using the master branch or unstable branch? 

I will take a look at the broken template app. To run samples please check out this repo: https://github.com/forcedotcom/SalesforceMobileSDK-WIndowsSamples

Can you please explain what you mean by connected services?

**Comment by imanpeeman** [comment] 2016-02-05 20:12
@kchitalia Thanks for your response!

Connected services: as described in https://developer.salesforce.com/blogs/developer-relations/2014/11/nothing-net-connected-service.html this doesn't work anymore, adding a connected service to an Universal App fails.

Adding the GitHub package SalesForce.SDK.Universal fails as well, the platform's aren't supported.
Grabbing a download of this repository and adding the Core and Univeral project to a new project succeeds (building the whole solution fails), however some examples are very welcome!

I Think all information on salesforce.com/Microsoft needs an update....

**Comment by kchitalia** [comment] 2016-05-06 19:55
@imanpeeman Connected Services is not supported by the Mobile SDK team. Plus, the connected service is meant for .NET apps, it does not support UWP.

Please take a look at the sample app [here ](https://github.com/forcedotcom/SalesforceMobileSDK-WindowsSamples/tree/master/Samples/Salesforce.Sample.SmartSyncExplorer)to see how you can add Core and Universal to your UWP app.

**Comment by helenren** [comment] 2016-09-21 16:49
We are working on the issues and hope to get the fix out soon. Thanks. @imanpeeman

**Comment by urthakkar** [comment] 2016-09-30 17:27
@imanpeeman thanks for your patience. We have updated the [Nuget package ](https://www.nuget.org/packages/Salesforce.SDK.Core/) to fix this issue.  Please use the unstable (our development) branch though since we are still in the middle of the release.

**Comment by huminzhi** [comment] 2016-10-10 18:36
The issue is fixed or solved in latest build.
Please try to reproduce again and see if it still exists. Thank you!

**Comment by huminzhi** [comment] 2016-10-10 18:41
@imanpeeman please let us know if you still see this with latest unstable branch.. otherwise, I am closing this issue..

**Closed by huminzhi** 2016-10-10 18:41 UTC
Labels: bug

**Comment by imanpeeman** [comment] 2016-10-10 19:43
Hi, Thanks for the update, but the link to the menitioned visual studio template in readme.rnd file is still broken... https://github.com/forcedotcom/SalesforceMobileSDK-Windows/blob/master/template/SalesforceUniversalApplicationTemplate.zip ==> should be https://github.com/forcedotcom/SalesforceMobileSDK-Windows/raw/master/SalesforceSDK/template/SalesforceUniversalApplicationTemplate.zip

beside that, creating a new project based on the template results in an error.
![projecterror](https://cloud.githubusercontent.com/assets/6469882/19248472/85717604-8f30-11e6-887f-4b86005d7307.PNG)

Missing some documentation on quick start (how to start with the SDK)

Thanks!
