### ISSUE TITLE
Error starting from template

### ISSUE THREAD

**Issue by danlb2000** [forcedotcom/SalesforceMobileSDK-Windows#216] opened 2016-06-19 00:01 UTC
When starting a new project with the template you receive the error "Error: this template attempted to load component assembly 'TemplateWizard, Version=1.0.0.0, Culture=Neutral, PublicKeyToken=69245b93ade9431a'. I see this problem in both Visual Studio 2015 release 2 and Visual Studio 2013.

**Comment by kchitalia** [comment] 2016-07-06 18:40
Are you trying this on the master branch or unstable branch?

**Comment by eklimanov** [comment] 2016-07-29 12:08
I agree with danlb2000. I have this problem too in master branch.

**Comment by kchitalia** [comment] 2016-08-03 18:44
Please try running the createapp.ps1 script from our unstable branch:
https://github.com/forcedotcom/SalesforceMobileSDK-Windows/tree/unstable/SalesforceSDK/template

**Comment by sanjeevdwivedi** [comment] 2016-09-07 17:56
Tried running the createapp.ps1. Trying to pass parameters to the powershell seems to always fail as the powershell keeps bringing up the powershell help script.. If you simply run the powershell with 'create' option, it prompts for the fields manually, which creates a project. However, the created project has a dependency on a version of nugets that are not yet published and everything fails.

**Comment by huminzhi** [comment] 2016-09-22 18:35
The issue is fixed or solved in latest build.
Please try to reproduce again and see if it still exists. Thank you!

**Comment by huminzhi** [comment] 2016-09-23 18:35
The issue is fixed or solved in latest build.
Please try to reproduce again and see if it still exists. Thank you!

**Comment by urthakkar** [comment] 2016-09-30 17:28
@danlb2000 @eklimanov @sanjeevdwivedi We have updated the [Nuget package ](https://www.nuget.org/packages/Salesforce.SDK.Core/) to fix this issue.  Please use the unstable (our development) branch though since we are still in the middle of the release.

**Comment by sanjeevdwivedi** [comment] 2016-09-30 19:18
the createapp.ps1 flow does not work unless you crack open it, look inside it and understand how the script works and then try to make it work by fighting it.

See here - even after supplying the requisite parameters, it just keeps ignoring everything that we are passing in.

![image](https://cloud.githubusercontent.com/assets/3850277/19003482/d5824b24-8705-11e6-952c-0bade0cfa4ec.png)

After opening it up and understanding that it requires a "create" parameter, when we pass the "create" parameter, it essentially ignores all the other parameters and assumes that they have not been passed in and starts prompting:

![image](https://cloud.githubusercontent.com/assets/3850277/19003828/71b065b6-8707-11e6-9e0c-29493439310c.png)

Even after we go down that path and we give it a path, unless the path already exists, it refuses to create the path, so the user had to go and create the path by themselves and pass it to  the script. See below:
![image](https://cloud.githubusercontent.com/assets/3850277/19003879/aac69744-8707-11e6-8810-166ea5b4541e.png)

After going through all the steps, a project does get created and it does work, but most users would give up at step one where the script does not honor the passed parameters and is actually expecting an unspecified "create" parameter that you can only know after you crack open the script and try to understand how it should be working.

**Comment by huminzhi** [comment] 2016-10-10 18:36
The issue is fixed or solved in latest build.
Please try to reproduce again and see if it still exists. Thank you!

**Comment by huminzhi** [comment] 2016-10-10 19:12
@sanjeevdwivedi Thank you for the info...
This pr should address your issue, and I am closing this issue.. let me know if any more question.
https://github.com/forcedotcom/SalesforceMobileSDK-Windows/pull/234/files

**Closed by huminzhi** 2016-10-10 19:12 UTC
Labels: bug
